using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Windows.Input;
using Decor.Core.DTOs;
using Decor.Core.Entities;
using Decor.Core.Interfaces.Services;
namespace Decor.AvaloniaUI.ViewModels;
public sealed class UsersViewModel : INotifyPropertyChanged, IStatusBarSource
{
 private readonly IUserAdministrationService service; private string _search="",_status="",_detailsStatus="",_toggleActiveConfirmationMessage=""; private bool _busy,_detailsBusy,_showToggleUserConfirmation,_pendingRequestedActiveState; private AdministrativeUserDTO? _selectedUser,_selectedDetails; private CancellationTokenSource? _detailsCancellation; private readonly RelayCommand _searchCommand,_clearSelectionCommand,_newUserCommand,_toggleActiveCommand,_confirmToggleActiveCommand,_cancelToggleActiveCommand; private int _pendingToggleUserId; public ObservableCollection<AdministrativeUserDTO> Users {get;}=[];
 public UsersViewModel(IUserAdministrationService service){this.service=service;_searchCommand=new RelayCommand(async()=>await LoadAsync(),()=>!IsBusy);_clearSelectionCommand=new RelayCommand(ClearSelection,()=>SelectedUser is not null);_newUserCommand=new RelayCommand(()=>NewUserRequested?.Invoke(this,EventArgs.Empty),()=>!IsBusy);_toggleActiveCommand=new RelayCommand(async()=>await ToggleActiveAsync(),()=>!IsBusy && SelectedUser is not null);_confirmToggleActiveCommand=new RelayCommand(async()=>await ConfirmToggleActiveAsync(),()=>!IsBusy && ShowToggleUserConfirmation);_cancelToggleActiveCommand=new RelayCommand(CancelToggleActive,()=>!IsBusy && ShowToggleUserConfirmation);}
 public ICommand SearchCommand => _searchCommand;
 public ICommand ClearSelectionCommand => _clearSelectionCommand;
 public ICommand NewUserCommand => _newUserCommand;
 public ICommand ToggleActiveCommand => _toggleActiveCommand;
 public ICommand ConfirmToggleActiveCommand => _confirmToggleActiveCommand;
 public ICommand CancelToggleActiveCommand => _cancelToggleActiveCommand;
 public string SearchText {get=>_search;set=>Set(ref _search,value);} public string StatusMessage {get=>_status;private set=>Set(ref _status,value);} public string? StatusPrimary=>null; public string? StatusSecondary=>null; public bool HasStatusPrimary=>false; public bool HasStatusSecondary=>false; public string? PaginationStatus=>null; public string? PaginationPageStatus=>null; public bool HasPagination=>false; public ICommand? PreviousPageCommand=>null; public ICommand? NextPageCommand=>null; public ICommand? FirstPageCommand=>null; public ICommand? LastPageCommand=>null; public bool HasPreviousPage=>false; public bool HasNextPage=>false; public bool HasFirstPage=>false; public bool HasLastPage=>false; public IReadOnlyList<int> PageSizeOptions=>[]; public int SelectedPageSize {get=>0;set{}}
 public bool IsBusy {get=>_busy;private set{if(Set(ref _busy,value)){_searchCommand.RaiseCanExecuteChanged();_newUserCommand.RaiseCanExecuteChanged();_toggleActiveCommand.RaiseCanExecuteChanged();_confirmToggleActiveCommand.RaiseCanExecuteChanged();_cancelToggleActiveCommand.RaiseCanExecuteChanged();}}}
 public bool IsDetailsBusy {get=>_detailsBusy;private set=>Set(ref _detailsBusy,value);}
 public AdministrativeUserDTO? SelectedUser {get=>_selectedUser;set{if(!Set(ref _selectedUser,value))return;_detailsCancellation?.Cancel();_detailsCancellation?.Dispose();_detailsCancellation=null;IsDetailsBusy=false;SelectedDetails=null;DetailsStatus="";OnPropertyChanged(nameof(HasDetails));OnPropertyChanged(nameof(HasDetailsError));OnPropertyChanged(nameof(ToggleActiveButtonText));_clearSelectionCommand.RaiseCanExecuteChanged();_toggleActiveCommand.RaiseCanExecuteChanged(); if(value is not null)_=LoadDetailsAsync(value.UserID);}}
 public AdministrativeUserDTO? SelectedDetails {get=>_selectedDetails;private set{if(Set(ref _selectedDetails,value)){OnPropertyChanged(nameof(HasDetails));OnPropertyChanged(nameof(HasDetailsError));}}}
 public bool HasDetails=>SelectedDetails is not null;
 public string DetailsStatus {get=>_detailsStatus;private set{if(Set(ref _detailsStatus,value)){OnPropertyChanged(nameof(HasDetailsError));}}}
 public bool HasDetailsError=>!string.IsNullOrWhiteSpace(DetailsStatus);
 public bool ShowToggleUserConfirmation {get=>_showToggleUserConfirmation;private set{if(Set(ref _showToggleUserConfirmation,value)){_confirmToggleActiveCommand.RaiseCanExecuteChanged();_cancelToggleActiveCommand.RaiseCanExecuteChanged();OnPropertyChanged(nameof(ToggleActiveConfirmationMessage));}}}
 public string ToggleActiveButtonText => SelectedUser is not null && SelectedUser.IsActive ? "Desativar usuário" : "Ativar usuário";
 public string ToggleActiveConfirmationMessage => _toggleActiveConfirmationMessage;
 public event EventHandler? NewUserRequested;
 public async Task HandleUserCreatedAsync(string username){await LoadAsync();SelectedUser=Users.FirstOrDefault(user=>user.Username.Equals(username,StringComparison.Ordinal));}
 public async Task InitializeAsync()=>await LoadAsync();
 private async Task LoadAsync(){IsBusy=true;try{var values=await service.SearchAsync(SearchText);Users.Clear();foreach(var item in values)Users.Add(item);StatusMessage=$"{Users.Count} usuário(s).";}catch(Exception){StatusMessage="Não foi possível carregar os usuários.";}finally{IsBusy=false;}}
 private async Task LoadDetailsAsync(int userId){var cancellation=new CancellationTokenSource();_detailsCancellation=cancellation;IsDetailsBusy=true;DetailsStatus="";try{var details=await service.GetByIdAsync(userId,cancellation.Token);if(cancellation.IsCancellationRequested||SelectedUser?.UserID!=userId)return;SelectedDetails=details; if(details is null)DetailsStatus="Os detalhes do usuário não foram encontrados.";}catch(OperationCanceledException) when(cancellation.IsCancellationRequested){}catch(Exception){if(!cancellation.IsCancellationRequested&&SelectedUser?.UserID==userId){SelectedDetails=null;DetailsStatus="Não foi possível carregar os detalhes do usuário.";}}finally{if(!cancellation.IsCancellationRequested&&SelectedUser?.UserID==userId)IsDetailsBusy=false;if(ReferenceEquals(_detailsCancellation,cancellation))_detailsCancellation=null;cancellation.Dispose();}}
 private void ClearSelection()=>SelectedUser=null;
 private async Task ToggleActiveAsync(){ if(SelectedUser is null) return; if(SelectedUser.IsActive){_pendingToggleUserId=SelectedUser.UserID;_pendingRequestedActiveState=false;_toggleActiveConfirmationMessage=$"Deseja realmente desativar o usuário \"{SelectedUser.Username}\"?";ShowToggleUserConfirmation=true; return;} await ExecuteToggleActiveAsync(SelectedUser.UserID,true); }
 private async Task ConfirmToggleActiveAsync(){ if(_pendingToggleUserId == 0 && SelectedUser is null) return; var userId = _pendingToggleUserId != 0 ? _pendingToggleUserId : SelectedUser!.UserID; var requestedActiveState = _pendingToggleUserId != 0 ? _pendingRequestedActiveState : !SelectedUser!.IsActive; ShowToggleUserConfirmation=false; await ExecuteToggleActiveAsync(userId, requestedActiveState); }
 private void CancelToggleActive(){ _pendingToggleUserId=0; _pendingRequestedActiveState=false; _toggleActiveConfirmationMessage=""; ShowToggleUserConfirmation=false; }
 private async Task ExecuteToggleActiveAsync(int userId,bool requestedActiveState){ IsBusy=true; try{ await service.SetActiveAsync(userId, requestedActiveState); StatusMessage = requestedActiveState ? "Usuário ativado com sucesso." : "Usuário desativado com sucesso."; await LoadAsync(); var restored = Users.FirstOrDefault(u => u.UserID == userId); SelectedUser = restored; if (restored is not null) { SelectedDetails = null; _ = LoadDetailsAsync(restored.UserID); } else { SelectedDetails = null; } }catch(UnauthorizedAccessException){StatusMessage="Você não possui permissão para esta operação.";}catch(InvalidOperationException ex){StatusMessage=ex.Message;}catch(Exception){StatusMessage="Não foi possível atualizar o estado do usuário.";}finally{ IsBusy=false; _pendingToggleUserId=0; _pendingRequestedActiveState=false; _toggleActiveConfirmationMessage=""; ShowToggleUserConfirmation=false; _toggleActiveCommand.RaiseCanExecuteChanged(); }}
 public event PropertyChangedEventHandler? PropertyChanged; private void OnPropertyChanged([CallerMemberName]string? n=null)=>PropertyChanged?.Invoke(this,new(n)); private bool Set<T>(ref T f,T v,[CallerMemberName]string? n=null){if(EqualityComparer<T>.Default.Equals(f,v))return false;f=v;OnPropertyChanged(n);return true;}
}
