<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Decor.Application/Decor.Application.csproj" />
    <ProjectReference Include="../../src/Decor.Infrastructure/Decor.Infrastructure.csproj" />
  </ItemGroup>
</Project>