<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.7" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.7" />
    <PackageReference Include="MySqlConnector" Version="2.4.0" />
    <PackageReference Include="Scrutor" Version="6.1.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Decor.Core\Decor.Core.csproj" />
    <ProjectReference Include="..\Decor.FluentSqlBuilder\Decor.FluentSqlBuilder.csproj" />
  </ItemGroup>

</Project>
