namespace Decor.Core.Common;

/// <summary>Deterministic source for restoring system roles; it never depends on their current database state.</summary>
public static class SystemRoleDefaults
{
    public const string Administrators = "Administradores";
    public const string Supervisors = "Supervisores";
    public static readonly IReadOnlyDictionary<string, IReadOnlyCollection<string>> Permissions =
        new Dictionary<string, IReadOnlyCollection<string>>(StringComparer.OrdinalIgnoreCase)
        {
            [Administrators] = [DecorPermissions.ProductsView, DecorPermissions.ProductsCreate, DecorPermissions.ProductsEdit, DecorPermissions.BrandsView, DecorPermissions.BrandsCreate, DecorPermissions.BrandsEdit, DecorPermissions.BrandsDelete, DecorPermissions.ClassificationsView, DecorPermissions.TermDeliveryView, DecorPermissions.UsersView, DecorPermissions.UsersCreate, DecorPermissions.UsersEdit, DecorPermissions.UsersActivate, DecorPermissions.UsersDeactivate, DecorPermissions.UsersAssignRoles, DecorPermissions.UsersManagePermissions, DecorPermissions.UsersResetPassword, DecorPermissions.UsersRestorePermissions, DecorPermissions.RolesView, DecorPermissions.RolesEdit, DecorPermissions.RolesManagePermissions, DecorPermissions.RolesRestoreDefaults, DecorPermissions.DatabaseMaintenanceView, DecorPermissions.CashAccountsView, DecorPermissions.CashAccountsCreate, DecorPermissions.CashAccountsUpdate, DecorPermissions.CashAccountsDeactivate, DecorPermissions.CashTransactionsView, DecorPermissions.CashTransactionsCreate, DecorPermissions.ProductSpecificationAttributesView, DecorPermissions.ProductSpecificationAttributesCreate, DecorPermissions.ProductSpecificationAttributesEdit, DecorPermissions.ProductSpecificationAttributesDelete, DecorPermissions.ProductKitComponentsView, DecorPermissions.ProductKitComponentsCreate, DecorPermissions.ProductKitComponentsEdit, DecorPermissions.ProductKitComponentsDelete, DecorPermissions.PartnerPriceTablesView, DecorPermissions.PartnerPriceTablesCreate, DecorPermissions.PartnerPriceTablesEdit, DecorPermissions.PartnerPriceTablesDelete, DecorPermissions.QuotesView, DecorPermissions.QuotesCreate, DecorPermissions.QuotesEdit, DecorPermissions.QuotesDelete, DecorPermissions.QuotesSend, DecorPermissions.QuotesApprove, DecorPermissions.UnitsOfMeasureView, DecorPermissions.UnitsOfMeasureCreate, DecorPermissions.UnitsOfMeasureEdit, DecorPermissions.UnitsOfMeasureDeactivate],
            [Supervisors] = [DecorPermissions.UsersView, DecorPermissions.UsersCreate, DecorPermissions.UsersEdit, DecorPermissions.UsersActivate, DecorPermissions.UsersDeactivate, DecorPermissions.UsersAssignRoles, DecorPermissions.UsersManagePermissions, DecorPermissions.UsersResetPassword, DecorPermissions.RolesView, DecorPermissions.RolesEdit, DecorPermissions.RolesManagePermissions, DecorPermissions.DatabaseMaintenanceView]
        };
}
