using Decor.Core.Common;
using Decor.Core.DTOs;
using Decor.Core.Entities;
using Decor.Core.Interfaces.Repositories;
using Decor.Core.Interfaces.Services;
namespace Decor.Application.Services;
public sealed class RoleAdministrationService(IUserAdministrationRepository users, IRoleAdministrationRepository roles, IAuthenticatedUserContext context, IAuthorizationService authorization) : IRoleAdministrationService
{
 public async Task<IReadOnlyList<AdministrativeRoleDTO>> GetRolesAsync(CancellationToken ct=default) { Require(DecorPermissions.RolesView); return await users.GetRolesAsync(ct); }
 public async Task<IReadOnlyList<AdministrativePermissionDTO>> GetPermissionsAsync(int roleId,CancellationToken ct=default) { Require(DecorPermissions.RolesView); await Target(roleId,ct); return await roles.GetPermissionsAsync(roleId,ct); }
 public async Task ReplacePermissionsAsync(int roleId,IReadOnlyCollection<int> permissionIds,CancellationToken ct=default) { Require(DecorPermissions.RolesManagePermissions); var role=await Target(roleId,ct); var all=await users.GetPermissionsAsync(ct); var codes=all.Where(p=>permissionIds.Contains(p.PermissionID)).Select(p=>p.PermissionCode).ToArray(); foreach(var code in codes)Require(code); if(role.IsSystemProtected&&role.RoleName.Equals(SystemRoleDefaults.Administrator,StringComparison.OrdinalIgnoreCase)){var required=SystemRoleDefaults.Permissions[SystemRoleDefaults.Administrator];if(required.Any(code=>!codes.Contains(code,StringComparer.OrdinalIgnoreCase)))throw new InvalidOperationException("A role Administrador deve preservar as permissões mínimas de recuperação.");} await roles.ReplacePermissionsAsync(roleId,permissionIds,ct); SignOutIfCurrentUserHasRole(role); }
 public async Task RestoreDefaultsAsync(int roleId,CancellationToken ct=default) { Require(DecorPermissions.RolesRestoreDefaults); var role=await Target(roleId,ct); if(!SystemRoleDefaults.Permissions.TryGetValue(role.RoleName,out var codes)) throw new InvalidOperationException("Esta role não possui padrão de sistema."); var all=await users.GetPermissionsAsync(ct); await roles.ReplacePermissionsAsync(roleId,all.Where(p=>codes.Contains(p.PermissionCode,StringComparer.OrdinalIgnoreCase)).Select(p=>p.PermissionID).ToArray(),ct); SignOutIfCurrentUserHasRole(role); }
 private void Require(string p){if(!context.IsAuthenticated||!authorization.HasPermission(p))throw new UnauthorizedAccessException("Você não possui permissão para esta operação administrativa.");}
 private void SignOutIfCurrentUserHasRole(AdministrativeRoleDTO role){if(context.User?.Roles.Contains(role.RoleName,StringComparer.OrdinalIgnoreCase)==true)context.SignOut();}
 private async Task<AdministrativeRoleDTO> Target(int id,CancellationToken ct){var rolesList=await users.GetRolesAsync(ct);var role=rolesList.SingleOrDefault(r=>r.RoleID==id)??throw new InvalidOperationException("Role não encontrada.");var assigned=rolesList.Where(r=>context.User!.Roles.Contains(r.RoleName,StringComparer.OrdinalIgnoreCase)).ToArray();var isAdmin=assigned.Any(r=>r.IsSystemProtected&&r.RoleName.Equals(SystemRoleDefaults.Administrator,StringComparison.OrdinalIgnoreCase));var level=assigned.Select(r=>r.HierarchyLevel).DefaultIfEmpty(0).Max();if(!isAdmin&&role.HierarchyLevel>=level)throw new UnauthorizedAccessException("A hierarquia não permite administrar esta role.");return role;}
}
